version: "3.3"

services:
    api-gateway:
        image: ${REGISTRY}-apigateway:master
        container_name: apigateway
        depends_on:
            - contentservice
            - userservice
            - playlistservice
        environment:
            SERVE_REST_ADDRESS: :8001
            CONTENT_SERVICE_GRPC_ADDRESS: contentservice:8002
            USER_SERVICE_GRPC_ADDRESS: userservice:8002
            PLAYLIST_SERVICE_GRPC_ADDRESS: playlistservice:8002
        ports:
            - 8001:8001

    contentservice:
        image: ${REGISTRY}-contentservice:master
        container_name: contentservice
        depends_on:
            - db
            - rabbitmq
            - userservice
        environment:
            SERVE_REST_ADDRESS: :8001
            SERVE_GRPC_ADDRESS: :8002
            DB_USER: root
            DB_PASSWORD: 1234
            DB_HOST: contentservice-db
            DB_NAME: contentservice
            AMQP_HOST: rabbitmq
            AMQP_USER: guest
            AMQP_PASSWORD: guest
            USER_SERVICE_GRPC_ADDRESS: userservice:8002

    userservice:
        image: ${REGISTRY}-userservice:master
        container_name: userservice
        depends_on:
            - db
            - rabbitmq
        environment:
            SERVE_REST_ADDRESS: :8001
            SERVE_GRPC_ADDRESS: :8002
            DB_USER: root
            DB_PASSWORD: 1234
            DB_HOST: userservice-db
            DB_NAME: userservice
            AMQP_HOST: rabbitmq
            AMQP_USER: guest
            AMQP_PASSWORD: guest

    playlistservice:
        image: ${REGISTRY}-playlistservice:master
        container_name: playlistservice
        depends_on:
            - db
            - contentservice
            - rabbitmq
        environment:
            SERVE_REST_ADDRESS: :8001
            SERVE_GRPC_ADDRESS: :8002
            DB_USER: root
            DB_PASSWORD: 1234
            DB_HOST: playlistservice-db
            DB_NAME: playlistservice
            AMQP_HOST: rabbitmq
            AMQP_USER: guest
            AMQP_PASSWORD: guest

    db:
        image: percona
        container_name: services-db
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - 3306:3306
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test: mysql -h127.0.0.1 -uroot -p1234 -e 'SELECT 1'
            interval: 20s
            timeout: 1s
        networks:
            default:
                aliases:
                    - contentservice-db
                    - userservice-db
                    - playlistservice-db

    rabbitmq:
        image: "rabbitmq:3.8-management"
        container_name: services-rabbitmq
        hostname: services-rabbitmq
        ports:
            - "15672:15672"
        volumes:
            - "mq:/var/lib/rabbitmq/mnesia"

volumes:
    db:
    mq: