version: "3.3"

services:
    api-gateway:
        image: vadimmakerov/apigateway:master
        container_name: apigateway
        environment:
            SERVE_REST_ADDRESS: :8001
            CONTENT_SERVICE_GRPC_ADDRESS: contentservice:8002
        ports:
            - 8001:8001

    contentservice:
        image: vadimmakerov/contentservice:master
        container_name: contentservice
        depends_on:
            - db
            - rabbitmq
            - api-gateway
        environment:
            CONTENTSERVICE_DSN: root:1234@/contentservice
            SERVE_REST_ADDRESS: :8001
            SERVE_GRPC_ADDRESS: :8002
            DB_USER: root
            DB_PASSWORD: 1234
            DB_HOST: contentservice-db
            DB_NAME: contentservice
            AMQP_HOST: rabbitmq
            AMQP_USER: guest
            AMQP_PASSWORD: guest

    db:
        image: percona
        container_name: services-db
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - 3306:3306
        volumes:
            - db:/var/lib/mysql
        healthcheck:
            test: mysql -h127.0.0.1 -uroot -p1234 -e 'SELECT 1'
            interval: 20s
            timeout: 1s
        networks:
            default:
                aliases:
                    - contentservice-db

    rabbitmq:
        image: "rabbitmq:3.8-management"
        container_name: services-rabbitmq
        hostname: services-rabbitmq
        ports:
            - "15672:15672"
        volumes:
            - "mq:/var/lib/rabbitmq/mnesia"

volumes:
    db:
    mq: